### ISSUE TITLE
Add memberPermissions table

### ISSUE THREAD

**Issue by jzongker** [LiveChurchSolutions/MembershipApi#26]
We need a way to grant members access to specific pieces of content - mainly forms and reports.  This is different than the roles/permissions managed by AccessApi.  Those grant access to broad types of actions, where this is granting access to one specific piece of content.  Only admin users can view/edit the role permissions in AccessApi.  For these memberPermissions, non-admin members will be granting other members access to content they create.

Create a memberPermissions table (id, memberId, contentType, contentId, action) and the associated model/repository/controller.  The rules for who can edit these records are:

- If there are no records yet for a contentType/contentId combination, any authenticated user can claim it.  Doing so adds a row with action of "admin" and their member id.
- If there already is a record for contentType/contentId only a member with "admin" permission can add other "admin" records or "view" records.

**Comment by jzongker** [comment]
@tec7z7 It appears this was completed two months ago with https://github.com/LiveChurchSolutions/MembershipApi/commit/d473a81e28388aa6075e521afab8d3e5cd760d89 .  Is this still in progress?

**Comment by tec7z7** [comment]
Correct, @jzongker. This has been completed.
