### ISSUE TITLE
Search broken when unicode characters are present

### ISSUE THREAD

**Issue by PhotoPaul** [LiveChurchSolutions/MembershipApi#55]
When searching for a member and there are Unicode characters included in the "term" param, the membership api returns an HTTP ERROR 400
e.g. https://membershipapi.churchapps.org/people/search?term=%u03B2%u03B1%u03C3

**Comment by jzongker** [comment]
Added a POST option for the people search.  https://github.com/LiveChurchSolutions/MembershipApi/commit/5eef4bfb409caac18b657ebb6407b9b643e24db6
